name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r pre-requirements.txt
        pip install -r requirements.txt
        pip install pytest-xvfb pytest-qt
    - name: pytest w/ test data
      run: |
        pip install pytest
        sudo apt-get update
        # install test data
        sudo apt-get install wget unzip
        wget -P ~ https://zenodo.org/record/5147737/files/DICOM-RT-01.zip
        mkdir test/testdata
        mkdir test/batchtestdata
        unzip ~/DICOM-RT-01.zip -d test/testdata
        unzip ~/DICOM-RT-01.zip -d test/batchtestdata
        sudo chmod -R 777 test/testdata
        sudo chmod -R 777 test/batchtestdata
        python -m pytest main.py
